version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - 8080:80
    volumes:
      - ./data:/code/data
    depends_on:
      migrations:
        condition: service_completed_successfully
  migrations:
    build:
      context: .
    volumes:
      - ./data:/code/data
    command: flask db upgrade
