version: "3.9"

services:
  app:
    image: sermalenk/skypro-flask-app:version-4
    ports:
      - 80:80
    volumes:
      - ./data:/code/data
    depends_on:
      migrations:
        condition: service_completed_successfully
  migrations:
    image: sermalenk/skypro-flask-app:version-4
    volumes:
      - ./data:/code/data
    command: flask db upgrade
